---
# tasks file for php

# - name: Enable remi repo for PHP 7.3.
#   set_fact: php_enablerepo="remi,remi-php73"
#   when: php_version == "7.3"

- name: Add remi-php71
  yum_repository:
    name: remi-php73
    description: Remi's PHP 7.1 RPM repository for Enterprise Linux $releasever - $basearch
    mirrorlist: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    enabled: yes
    gpgcheck: 1
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi

- name: Install yum utils 
  yum: 
    name: yum-utils 
    state: present 
  become: yes 

- name: Disable installation of php 54 
  shell: yum-config-manager --disable remi-php54
  become: yes 

- name: Enable installation of php73
  shell: yum-config-manager --enable remi-php73
  become: yes 

- name: Install php extensions
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - php
    - php-mysql
    - php-gd
    - php-ssh2
    - php-mcrypt

# - name: Setup php-fpm
#   replace: dest=/etc/php/7.0/fpm/php.ini regexp="(;cgi.fix_pathinfo=1)" replace="cgi.fix_pathinfo=0"
#   notify:
#     - restart nginx
#   become: yes

# - name: Add php settings
#   template: src=../../nginx/templates/nginx-wp-common.conf dest=/etc/nginx/nginx-wp-common.conf owner=www-data group=www-data mode=0644
#   notify:
#     - restart nginx
#   become: yes
